### ISSUE TITLE
Dist files don't contain fixes, build process error

### ISSUE THREAD

**Issue by adamdburton** [c-frame/aframe-extras#367]
The minified files in this repo are missing a couple of fixes that have been merged recently. When trying to build to make a PR I get the error below using `three@0.130.1` - `three@0.133.1`.

```
➜ npm run build

> aframe-extras@6.1.1 build /home/adam/Sites/aframe-extras
> browserify index.js -o examples/bundle.js -t [ babelify --presets [ env ] ]

SyntaxError: Unexpected token (1962:26) while parsing /home/adam/Sites/aframe-extras/node_modules/three/build/three.js while parsing file: /home/adam/Sites/aframe-extras/node_modules/three/build/three.js
    at DestroyableTransform.end [as _flush] (/home/adam/Sites/aframe-extras/node_modules/insert-module-globals/index.js:96:21)
    at DestroyableTransform.<anonymous> (/home/adam/Sites/aframe-extras/node_modules/insert-module-globals/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:138:49)
    at Object.onceWrapper (events.js:519:28)
    at DestroyableTransform.emit (events.js:400:28)
    at prefinish (/home/adam/Sites/aframe-extras/node_modules/insert-module-globals/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:596:14)
    at finishMaybe (/home/adam/Sites/aframe-extras/node_modules/insert-module-globals/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:604:5)
    at endWritable (/home/adam/Sites/aframe-extras/node_modules/insert-module-globals/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:615:3)
    at DestroyableTransform.Writable.end (/home/adam/Sites/aframe-extras/node_modules/insert-module-globals/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:571:41)
    at DestroyableTransform.onend (/home/adam/Sites/aframe-extras/node_modules/module-deps/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:519:28)
```

Any help to update the dist files would be appreciated.

**Comment by vincentfretin** [comment]
There is a new build on master.
